== Processi applicativi (((8. Processi applicativi)))

Tutti i documenti in transito su NoTI-ER vengono associati ad un *ciclo di vita* ben definito, che dipende del tipo
di processo di e-Procurement  (Inbound o Outbound) e dall'instradamento da e verso i sistemi integrati (SdI, Peppol, NSO e ParER).

=== Stati e Sessioni

Per rappresentare le varie fasi del processo di e-Procurement in cui un documenti si trova, è stato definito un insieme numerabile di *stati*. +
La sequenza di tutte le *transizioni tra stati* che un documento ha trascorso costituisce il _ciclo di vita dello stesso in NoTI-ER_. +
A partire dall'insieme complessivo di _stati_, sono state individuate alcune _collezioni_ che vengono chiamate *sessioni*. In particolare,
le _sessioni_ di un documento sono _collezioni di stati che descrivono il transito di un documento in NoTI-ER declinato in una specifica direzione._ +
Pertanto, un documento è associato in maniera _mutualmente esclusiva_ ad una:

* *sessione di invio*: insieme di tutti gli stati che descrivono il processo di Outbound, in cui un documento viene emesso da un soggetto iscritto a NoTi-ER
e instradato verso verso il sistema di destinazione.
* *sessione di ricezione*: insieme di tutti gli stati che descrivono il processo di Inbound, in cui NoTI-ER riceve un documento, proveniente da SdI o Peppol, per poter essere messo
a disposizione dell'ufficio ricevente.

Entrambe le sessioni si scindono in riferimento al sistema di integrazione. Avremo, dunque, delle sessioni di invio e di ricezione _da e verso SdI_, oppure _da e verso Peppol._ +
A queste si possono aggiungere:

* #*sessione di invio a NSO*#: è una sessione complementare alla _sessione di invio_ e comprende gli stati che descrivono il processo di scambio con NSO.
In particolare, un ordine emesso da una Azienda Sanitaria, che viene inviato al destinatario su rete Peppol,
viene contemporaneamente inviato anche ad NSO per adempiere agli obblighi di validazione previsti. footnote:[vedi il <<anchor-4, paragrafo 5.3. Integrazione con NSO.>>]
* *sessione di conservazione*: è l'insieme degli stati che descrivono il versamento in ParER di un documento, indipendentemente dal processo di e-Procurement.

Ulteriormente, considerato che il ciclo di vita di un documento non termina con il singolo transito su NoTI-ER, ma prosegue a seguito dell'integrazione con gli altri sistemi,
sono state definite _collezioni di stati specifici del documento stesso_, sempre in riferimento
alla direzione di instradamento.

Nei paragrafi che seguono, viene mostrata una panoramica di quelli che sono gli stati associati ad ogni sessione, a livello di _stato della sessione_ e di _stato del documento_ corrispondente.

==== Sessione di invio

La tabella sottostante mostra tutti gli _stati_ associati al dominio _sessione di invio_, la descrizione dello
stato della sessione e il relativo _stato del documento_.

.Sessione di invio e relativi stati
[width="85%",cols="^,^,^,^">,options="header,footer"]
|===
|Stato ^|Tipo Stato| Descrizione Stato | Stato Documento
^.^|DA_TRASFORMARE ^.^|INIZIALE ^.^| Documento da trasformare da formato UBL a formato SdI ^.^|IN_ELABORAZIONE
^.^|NON_VALIDO ^.^|INIZIALE_FINALE ^.^| Documento non valido ^.^| ELABORATO_KO +
NON_ACCETTATO
^.^|DA_INVIARE_SDI ^.^|INIZIALE ^.^| Documento SdI firmto e approvato da inviare a SdI ^.^| IN_ELABORAZIONE
^.^|DA_FIRMARE ^.^|INTERMEDIO ^.^| Documento in formato SdI da firmare ^.^| IN_ELABORAZIONE
^.^|DA_APPROVARE ^.^|INTERMEDIO ^.^| Documento in formato SdI firmato da approvare ^.^| IN_ELABORAZIONE
^.^|IN_LAVORAZIONE ^.^| INTERMEDIO ^.^| Documento in lavorazione a seguito di anomalia applicativa ^.^| ELABORATO_KO +
IN_ELABORAZIONE
^.^|SCARTATO ^.^|FINALE_INTERMEDIO ^.^| Documento SdI firmato scartato ^.^| ELABORATO_KO +
IN_ELABORAZIONE
^.^|INVIATO_SDI ^.^|FINALE_INTERMEDIO ^.^| Documento SdI inviato a SdI ^.^| x
^.^|DA_INOLTRARE_BUSDOX ^.^|INIZIALE ^.^| Documento da inoltrare su rete Peppol ^.^| x
^.^|ATTESA_VALIDAZIONE ^.^|INIZIALE ^.^| Documento in attesa di esito da NSO prima di essere inoltrato su Peppol ^.^| x
^.^|BLOCCATO_DA_NSO ^.^|FINALE ^.^| Documento bloccato a fronte della ricezione dell'esito di validazione negativo da NSO ^.^| x
^.^|INVIATO_BUSDOX ^.^|FINALE ^.^| Documento inoltrato su rete Peppol ^.^| x
^.^|NON_INVIATO_BUSDOX ^.^|FINALE ^.^| Documento non inoltrato correttamente su rete Peppol causa anomalia applicativa ^.^| x
^.^|DA_INVIARE_NSO ^.^|INIZIALE ^.^| Documento da inviare verso NSO ^.^| x
^.^|INVIATO_NSO ^.^|INTERMEDIO ^.^| Documento inviato a NSO ^.^| x
^.^|CONSEGNATO_NSO ^.^|FINALE ^.^|Documento consegnato a NSO e validato dallo stesso ^.^| x
^.^|SCARTATO_NSO ^.^|FINALE ^.^| Documento inviato ad NSO e scartato dallo stesso ^.^| x
^.^|NON_INVIATO_NSO ^.^|FINALE ^.^| Documento non inviato NSO causa anomalia applicativa ^.^| x
^.^|DA_NON_INVIARE_NSO ^.^|FINALE ^.^| Documento da non inviare a NSO ^.^| x
^.^| ^.^| ^.^|  ^.^|
|===


==== Sessione di ricezione

La tabella sottostante mostra tutti gli _stati_ associati al dominio _sessione di ricezione_, la descrizione dello
stato della sessione e il relativo _stato del documento_.

.Sessione di ricezione e relativi stati
[width="85%",cols="^,^,^,^">,options="header,footer"]
|===
|Stato ^|Tipo Stato| Descrizione Stato | Stato Documento
^.^|DA_TRASFORMARE ^.^|INIZIALE ^.^| Documento da trasformare da SdI a UBL  ^.^|
^.^|TEMPORANEO_INBOUND ^.^|INIZIALE ^.^| Documento ricevuto con problematiche sulla validazione  ^.^|
^.^|DA_RECAPITARE ^.^|INIZIALE ^.^| Documento da recapitare a soggetto  ^.^|
^.^|RECAPITATO ^.^|FINALE ^.^| Documento recapitato al soggetto  ^.^|
^.^|NON_VALIDO ^.^|FINALE ^.^| Documento non valido  ^.^|
^.^| ^.^| ^.^|  ^.^|
|===

==== Sessione di conservazione

La tabella sottostante mostra tutti gli _stati_ associati al dominio _sessione di conservazione_, la descrizione dello
stato della sessione e il relativo _stato del documento_.

.Sessione di conservazione e relativi stati
[width="85%",cols="^,^,^,^">,options="header,footer"]
|===
|Stato ^|Tipo Stato| Descrizione Stato | Stato Documento
^.^|DA_NON_INVIARE ^.^|INIZIALE_FINALE ^.^| Documento da non inviare in conservazione  ^.^|
^.^|DA_INVIARE ^.^|INIZIALE ^.^|Documento da inviare in conservazione  ^.^|
^.^|DA_ANNULLARE ^.^|INIZIALE ^.^|Documento da annallure SACER  ^.^|
^.^|IN_ATTESA_DATI_FISCALI ^.^|INIZIALE ^.^|Documento in attesa di integrazione dei dati fiscali  ^.^|
^.^|ANNULLATO ^.^|INIZIALE_INTERMEDIO ^.^|Documento annullato SACER  ^.^|
^.^|INVIATO_OK ^.^|FINALE ^.^|Documento inviato in conservazione  ^.^|
^.^|INVIATO_KO ^.^|FINALE ^.^|Documento non inviato in conservazione causa anomalia applicativa  ^.^|
^.^|NON ANNULLABILE ^.^|FINALE ^.^|Documento non annullabile SACER  ^.^|
^.^| ^.^| ^.^|  ^.^|
|===

==== Transizioni di stati

Come già accennato ai paragrafi precedenti, _la sequenza di tutte le transizioni tra stati, che un documento e le rispettive sessioni subiscono, costituisce il
ciclo di vita del documento stesso._ +
Le transizioni fra stati avvengono in seguito al verificarsi di particolari eventi, che si possono distinguere in:

* *esterni*: sono innescati da attori esterni a NoTI-ER -come avviene, ad esempio, per la ricezione di un documento in NoTI-ER o per lo scarico di un documento da parte di un soggetto;
* *interni*: sono innescati da specifiche azioni che NoTI-ER esegue in momenti predeterminati.

Le transizioni tra stati possibili e innescate da eventi interni o esterni, che seguono le logiche funzionali di NoTI-ER, sono quelle descritte dalla tabella che segue.

.Transizioni fra stati di sessioni e documento
[width="85%",cols="^,^">,options="header,footer"]
|===
^.^| Stato d'Origine| Stato di Destinazione
2.1+s| SESSIONE DI INVIO
^.^|ATTESA_VALIDAZIONE ^.^| DA_INOLTRARE_BUSDOX
^.^|ATTESA_VALIDAZIONE ^.^| BLOCCATO_DA_NSO
^.^|DA_APPROVARE ^.^| DA_INVIARE_SDI
^.^|DA_APPROVARE ^.^| SCARTATO
^.^|DA_FIRMARE ^.^| DA_INVIARE_SDI
^.^|DA_FIRMARE ^.^| DA_APPROVARE
^.^|DA_INOLTRARE_BUSDOX ^.^| NON_INVIATO_BUSDOX
^.^|DA_INOLTRARE_BUSDOX ^.^| INVIATO_BUSDOX
^.^|DA_INVIARE_NSO ^.^| NON_INVIATO_NSO
^.^|DA_INVIARE_NSO ^.^| INVIATO_NSO
^.^|DA_INVIARE_SDI ^.^| INVIATO_SDI
^.^|DA_TRASFORMARE ^.^| IN_LAVORAZIONE
^.^|DA_TRASFORMARE ^.^| DA_FIRMARE
^.^|#IN_LAVORAZIONE# ^.^| NON_VALIDO
^.^|INVIATO_NSO ^.^| SCARTATO_NSO
^.^|INVIATO_NSO ^.^| CONSEGNATO_NSO
^.^|INVIATO_NSO ^.^| DA_INVIARE_NSO
^.^|INVIATO_SDI ^.^| DA_INVIARE_SDI
^.^|NON_INVIATO_BUSDOX ^.^| SCARTATO
^.^|NON_INVIATO_NSO ^.^| DA_INVIARE_NSO
^.^|SCARTATO ^.^| SCARTATO
^.^|SCARTATO_NSO ^.^| CONSEGNATO_NSO
^.^|SCARTATO_NSO ^.^| DA_INVIARE_NSO
2.1+s| SESSIONE DI RICEZIONE
^.^| DA_RECAPITARE ^.^| RECAPITATO
^.^| DA_TRASFORMARE ^.^| DA_RECAPITARE
^.^| DA_TRASFORMARE ^.^| IN_LAVORAZIONE
^.^| #IN_LAVORAZIONE# ^.^| NON_VALIDO
^.^| NON_VALIDO ^.^| RECAPITATO
^.^| TEMPORANEO_INBOUND ^.^| #IN_LAVORAZIONE#
^.^| TEMPORANEO_INBOUND ^.^| DA_RECAPITARE
2.1+s| SESSIONE DI CONSERVAZIONE
^.^| ANNULLATO ^.^| INVIATO_KO
^.^| ANNULLATO ^.^| INVIATO_OK
^.^| DA_ANNULLARE ^.^| NON_ANNULLABILE
^.^| DA_ANNULLARE ^.^| ANNULLATO
^.^| DA_INVIARE ^.^| INVIATO_KO
^.^| DA_INVIARE ^.^| INVIATO_OK
^.^| #IN_ATTESA_DATI_FISCALI# ^.^| DA_INVIARE
^.^| INVIATO_KO ^.^| ANNULLATO
^.^| INVIATO_OK ^.^| ANNULLATO
2.1+s| DOCUMENTO INVIO
^.^| CONSEGNATO ^.^| NON_ACCETTATO
^.^| CONSEGNATO ^.^| ACCETTATO
^.^| ELABORATO_KO ^.^| IN_ELABORAZIONE
^.^| IN_ELABORAZIONE ^.^| ELABORATO_KO
^.^| IN_ELABORAZIONE ^.^| NON_ACCETTATO
^.^| IN_ELABORAZIONE ^.^| INVIATO_BUSDOX
^.^| IN_ELABORAZIONE ^.^| NOTIFICATO_A_SDI
^.^| IN_ELABORAZIONE ^.^| INVIATO_SDI
^.^| INVIATO_SDI ^.^| ACCETTATO
^.^| INVIATO_SDI ^.^| IN_ELABORAZIONE
^.^| INVIATO_SDI ^.^| CONSEGNATO
^.^| INVIATO_SDI ^.^| NON_ACCETTATO
^.^| INVIATO_SDI ^.^| NON_CONSEGNATO
^.^| NON_ACCETTATO ^.^| CONSEGNATO
^.^| NON_CONSEGNATO ^.^| CONSEGNATO
2.1+s| DOCUMENTO RICEZIONE
^.^| IN_ELABORAZIONE ^.^| NON_CONGRUO
^.^| IN_ELABORAZIONE ^.^| NON_ACCETTATO
^.^| IN_ELABORAZIONE ^.^| ELABORATO_KO
^.^| IN_ELABORAZIONE ^.^| ELABORATO_OK
2.1+s| DOCUMENTO CONSERVAZIONE
^.^| DA_INVIARE ^.^| INVIATO_KO
^.^| DA_INVIARE ^.^| DA_NON_INVIARE
^.^| DA_INVIARE ^.^| INVIATO_OK
^.^| DA_NON_INVIARE ^.^| DA_INVIARE
^.^| INVIATO_KO ^.^| DA_INVIARE
^.^| INVIATO_KO ^.^| DA_NON_INVIARE
^.^| INVIATO_OK ^.^| DA_INVIARE
^.^| INVIATO_OK ^.^| DA_NON_INVIARE
^.^| ^.^|
|===


=====
.Eventi interni e job di NoTI-ER
In relazione all'innesco di transizioni da parte di eventi interni, NoTI-ER utilizza una logica basata sullo *scheduling*, in un'ottica di esecuzione massiva della stessa azione
su collezioni di documenti che si trovano nel medesimo stato. +
Per effettuare le operazioni appena descritte, NoTI-ER si serve dei seguenti *Job* footnote:[per Job si intende l'unità di lavoro che uno scheduler invia al sistema operativo.].

.Elenco dei Job di NoTI-ER
[width="85%",cols="^,^,^">,options="header,footer"]
|===
|Job ^| Azione | Condizione
^.^s| ANNULLA_CONSERVAZIONE ^.^| Esegue l'invio della richiesta di annullamento conservazione verso ParER  ^.^| Lo stato della sessione di conservazione del documento è DA_ANNULLARE
^.^s| FIRMA_REMOTA ^.^| Implementa l'azione di firma digitale dei documenti transcodificati in formato _fatturaPA_ ^.^| Lo stato della sessione di invio del documento è DA_FIRMARE
^.^s| INVIO_CONSERVAZIONE ^.^| Esegue l'invio in conservazione dei documenti ^.^| Lo stato della sessione di conservazione del documento è DA_INVIARE
^.^s| INVIO_NSO ^.^| Esegue l'invio dei documenti a NSO ^.^| Lo stato della sessione di invio ad NSO del documento è DA_INVIARE_NSO
^.^s| INVIO_SDI ^.^| Esegue l'invio dei documenti a SdI ^.^| Lo stato della sessione di invio SdI del documento è DA_INVIARE_SDI
^.^s| PREPARA_INVIO_PEPPOL_SCADENZEfootnote:[rilevante solo nel caso sia impostata la configurazione in cui un documento deve attendere la validazione da parte di NSO prima di essere inoltrato su rete Peppol.] ^.^| Imposta lo stato della sessione di invio Peppol in DA_INOLTRARE BUSDOX ^.^| Lo stato della sessione di invio Peppol è fermo in ATTESA_VALIDAZIONE da più del tempo configurato
^.^s| TRASFORMAZIONE_DOC_SDI_TO_UBL ^.^| Esegue la transcodifica dei documenti dal formato _fatturaPA_ al formato UBL ^.^| Lo stato della sessione di ricezione del documento è DA_TRASFORMARE
^.^s| TRASFORMAZIONE_DOC_UBL_TO_SDI ^.^| Esegue la transcodifica dei documenti dal formato UBL al formato _fatturaPA_ ^.^| Lo stato della sessione di invio del documento è DA_TRASFORMARE
^.^s| OUTBOUND_FLOW ^.^| Esegue l'invio su Peppol dei documenti ^.^| Lo stato della sessione di invio su Peppol del documento è DA_INOLTRARE_BUSDOX
^.^s| ^.^| ^.^|
|===
=====
